pipeline
{

    agent {
        label 'ProdServer'
    }
    parameters {
        string defaultValue: 'ProdSrver', name : 'DevServer'
    }
    environment {
     Name ="DevServer"
    }
    tools{
        maven 'mymaven'
    }
    stages{
         stage('Build')
        {
           
            steps{
                sh 'mvn clean package'
                echo "Build Success"
                echo "hello $NAME ${name}"
            }

        post {
             success {
                echo 'Build Success archiving.............'
                archiveArtifacts artifacts: '**/target/*.jar'
                    }
            }

        }
   
}
}