pipeline
{

    agent {
        label 'ProdServer'
    }
    parameters {
        string defaultValue: 'ProdSrver', name : 'DevServer'
    }
    environment {
     Name ="DevServer"
    }
    tools{
        maven 'mymaven'
    }
    stages{
         stage('Build')
        {
           
            steps{
                sh 'mvn clean package'
                echo "Build Success"
                echo "hello $NAME ${name}"
            }


        }
        stage('test')
        {
            parllel {
                stage('testA'){
                    steps{
                        echo "this is test A"
                    }
                }
                stage('testB'){
                    steps{
                        echo "this is test B"
                    }
                }
            }
        post {
             success {
                echo 'Build Success archiving.............'
                archiveArtifacts artifacts: '**/target/*.jar'
                    }
            }
        }
        
   
}
}