pipeline
{

    agent {
    label 'DevServer'
    }
    tools{
        maven 'mymaven'
    }
    stages{
         stage('Build')
        {
           
            steps{
                sh 'mvn clean package'
            }

        post {
             success {
                echo 'Build Success archiving.............'
                archiveArtifacts artifacts: '**/target/*.jar'
                    }
            }

        }
   
}
}